install requirements:
	pip install -r requirements.txt
docker-compose up -d:
	docker-compose up -d
postgres-initdb:
	python api.services.init_db
uvicorn api.main:app --reload:
	uvicorn api.main:app --reload	
Remove-Items -Path .\data\* -Recurse -Force:
	Remove-Item uploads -Recurse -Force
	Remove-Item rag_Storage -Recurse -Force
